name: Build SDK References Documents

on:
  push:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Restore gradle.properties
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        GRADLE_PROPERTIES: ${{ secrets.GRADLE_PROPERTIES }}
      shell: bash
      run: |
        mkdir -p ~/.gradle/
        echo "::set-env name=GRADLE_USER_HOME::$HOME/.gradle"
        echo ${GRADLE_PROPERTIES} > ~/.gradle/gradle.properties
    - name: Build
      run: |
        sh ./gradlew dokkaHtml
    - name: Commit and push docs
      working-directory: ./
      run: |
        git config --global user.email "wiley@nurigo.net"
        git config --global user.name "Github Actions"
        git add ./docs
        git commit -m "Update SDK API References"
        git push
