name: Build SDK References Documents

on:
  push:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Restore gradle.properties
      env:
        ACTIONS_ALLOW_UNSECURE_COMMANDS: true
        OSS_USERNAME: ${{ secrets.OSS_USERNAME }}
        OSS_PASSWORD: ${{ secrets.OSS_PASSWORD }}
      shell: bash
      run: 
        echo "ossusername="  > ./gradle.properties
        echo ${OSS_USERNAME} >> ./gradle.properties
        echo -e "\n" >> ./gradle.properties
        echo "osspassword="  >> ./gradle.properties
        echo ${OSS_PASSWORD} >> ./gradle.properties
    - name: Build
      run: |
        sh ./gradlew dokkaHtml
    - name: Commit and push docs
      working-directory: ./
      run: |
        git config --global user.email "wiley@nurigo.net"
        git config --global user.name "Github Actions"
        git add ./docs
        git commit -m "Update SDK API References"
        git push
