name: Build SDK References Documents

on:
  push:
    branches: [ main ]

jobs:
  build-docs:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Build
      run: |
        sh ./gradlew dokkaHtml
    - name: Commit and push docs
      working-directory: ./
      run: |
        git config --global user.email "wiley@nurigo.net"
        git config --global user.name "Github Actions"
        git add ./docs
        git commit -m "Update SDK API References"
        git push
